[package]
org = "user"
name = "server_bal"
version = "0.1.0"
distribution = "2201.12.7"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "persist"
version = "1.4.0"

[[dependency]]
org = "ballerinax"
name = "persist.postgresql"
version = "1.4.0"

[[dependency]]
org = "ballerinax"
name = "postgresql"
version = "1.13.0"

[[dependency]]
org = "ballerinax"
name = "postgresql.driver"
version = "1.6.0"

[[dependency]]
org = "ballerina"
name = "uuid"
version = "1.10.0"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.sql-native"
version = "1.6.0"

